SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

START TRANSACTION;

SET time_zone = "+00:00";

-- Base de données : `db_restoweb`
CREATE DATABASE IF NOT EXISTS `DB_RESTOWEB` DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE `DB_RESTOWEB`;

-- --------------------------------------------------------

-- Structure de la table `commande`
CREATE TABLE `COMMANDE` (
    `ID_COMMANDE` INT(11) NOT NULL,
    `ID_USER` INT(11) NOT NULL,
    `ID_ETAT` INT(11) NOT NULL,
    `DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `TOTAL_COMMANDE` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `TYPE_CONSO` TINYINT(1) NOT NULL,
    PRIMARY KEY (`ID_COMMANDE`),
    KEY `ID_USER` (`ID_USER`),
    KEY `ID_ETAT` (`ID_ETAT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;

-- Structure de la table `ligne`
CREATE TABLE `LIGNE` (
    `ID_LIGNE` INT(11) NOT NULL,
    `ID_COMMANDE` INT(11) NOT NULL,
    `ID_PRODUIT` INT(11) NOT NULL,
    `QTE` INT(11) NOT NULL DEFAULT 0,
    `TOTAL_LIGNE_HT` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PRIMARY KEY (`ID_LIGNE`),
    KEY `ID_COMMANDE` (`ID_COMMANDE`),
    KEY `ID_PRODUIT` (`ID_PRODUIT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;

-- Structure de la table `produit`
CREATE TABLE `PRODUIT` (
    `ID_PRODUIT` INT(11) NOT NULL,
    `LIBELLE` VARCHAR(255) NOT NULL,
    `PRIX_HT` DECIMAL(10, 2) NOT NULL,
    `IMAGEURL` VARCHAR(250) NOT NULL,
    PRIMARY KEY (`ID_PRODUIT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;

-- Structure de la table `user`
CREATE TABLE `USER` (
    `ID_USER` INT(11) NOT NULL,
    `LOGIN` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `EMAIL` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID_USER`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_GENERAL_CI;

-- Contraintes pour les tables
ALTER TABLE `COMMANDE`
    ADD CONSTRAINT `COMMANDE_IBFK_1` FOREIGN KEY (
        `ID_USER`
    )
        REFERENCES `USER` (
            `ID_USER`
        );

ALTER TABLE `LIGNE`
    ADD CONSTRAINT `LIGNE_IBFK_1` FOREIGN KEY (
        `ID_COMMANDE`
    )
        REFERENCES `COMMANDE` (
            `ID_COMMANDE`
        ), ADD CONSTRAINT `LIGNE_IBFK_2` FOREIGN KEY (
            `ID_PRODUIT`
        )
            REFERENCES `PRODUIT` (
                `ID_PRODUIT`
            );

COMMIT;